// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using VirtualMindServicesBackend.Data;

namespace VirtualMindServicesBackend.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VirtualMindServicesBackend.Dtos.TransaccionDto", b =>
                {
                    b.Property<Guid>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdUsuario")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("MonedaCompra")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("MontoCambioDia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoPesosArgentinos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTransaccion");

                    b.ToTable("Transaccion");
                });
#pragma warning restore 612, 618
        }
    }
}
